### ISSUE TITLE
[1.20.1] Console comands not reaching server

### ISSUE THREAD

**Issue by TerraPlayer1** [Lightman314/Lightmans-Discord-Integration#17] opened 2023-07-29 14:05 UTC
No commands written in the Console Channel work.
Server chat works as expected. 
Have tried switching channels: Server chat worked in what used to be the Console channel. Console still didn't work in what used to be the Server chat channel.

Forge: 1.20.1-47.1.0
LMDI: 1.20-0.2.0.0

**Comment by Lightman314** [comment] 2023-09-10 17:43
Found the cause. An update fixing this will be out shortly

**Comment by Lightman314** [comment] 2023-09-10 18:21
Fixed in LDI v0.2.0.1

**Closed as completed by Lightman314** 2023-09-10 18:21 UTC
